import { P } from "@clerk/clerk-react/dist/useAuth-DN6TRwS8";

export const ROLES = {
  ADMIN: "admin",
  MANAGER: "manager",
  USER: "user",
  GUEST: "guest",
};
export const PERMISSIONS = {
  VIEW_DASHBOARD: "view_dashboard",
  VIEW_PRODUCTS: "view_products",
  EDIT_PRODUCT: "edit_product",
  DELETE_PRODUCT: "delete_product",
};

export const ROLES_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCT,
    PERMISSIONS.DELETE_PRODUCT,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCT,
  ],
  [ROLES.USER]: [PERMISSIONS.VIEW_PRODUCTS, PERMISSIONS.VIEW_DASHBOARD],
  [ROLES.GUEST]: [PERMISSIONS.VIEW_DASHBOARD],
};
